# 0 is too far from ` ;)
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g history-limit 10000

setw -g mode-keys vi
setw -g monitor-activity on

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Enable mouse
setw -g mouse on

# Set clipboard
set -g set-clipboard on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Themes
set -g @plugin 'o0th/tmux-nova'
set -g @nova-interval 0.5
set -g @nova-nerdfonts true

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-test "echo "asd""
set -g @nova-segment-test-colors "#50fa7b #282a36"

# set -g @plugin 'o0th/milky'
# set -g @nova-status-right-plugins 'testing'
# set -g @plugin 'madlep/tmux'
# set -g @dracula-plugins "network-bandwidth"
# set -g @dracula-network-bandwidth "enp6s0"
# set -g @nova-theme 'dracula'
# set -g @nova-plugins-mode-labels "ω Ω"
# set -g @nova-plugins-mode-colors "#50fa7b #282a36"
# set -g @nova-plugins-whoami-colors "#50fa7b #282a36"
# set -g @nova-plugins-spotify-colors "#50fa7b #44475a"
# set -g @plugin 'o0th/tmux'

# Dracula theme options
# set -g @dracula-show-powerline true
# set -g @dracula-show-left-icon "Ω"
# set -g @dracula-left-icon-padding 0
# set -g @dracula-plugins "battery network-bandwith time"
# set -g @dracula-military-time true

# set -g @dracula-show-flags true
# set -g @dracula-ram-usage-label ﬙
# set -g @dracula-ram-usage-colors "dark_gray white"
# set -g @dracula-gpu-usage-label 
# set -g @dracula-gpu-usage-colors "dark_gray white"
# set -g @dracula-cpu-usage-label 
# set -g @dracula-cpu-usage-colors "dark_gray white"

# Set default shell
set-option -g default-shell /bin/fish

# Reload tmux config
bind r source-file ~/.tmux.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

